import { ImageResponse } from 'next/og';
import { supabaseAdmin } from "@/lib/supabase";

export const runtime = 'edge';
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

export default async function Image({ params }) {
  const { date } = await params;

  // 1. Fetch the data for the specific day
  const { data: brief } = await supabaseAdmin
    .from("daily_briefs")
    .select("summary, top_stories")
    .eq("date", date)
    .single();

  const primaryTitle = brief?.top_stories?.[0]?.title || "Daily Dev Brief";

  return new ImageResponse(
    (
      <div
        style={{
          height: '100%',
          width: '100%',
          display: 'flex',
          flexDirection: 'column',
          backgroundColor: '#050505', // Your deep black background
          padding: '50px',
          fontFamily: 'monospace',
        }}
      >
        {/* Signal Bar Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid #1a1a1a', paddingBottom: '20px', marginBottom: '40px' }}>
          <div style={{ display: 'flex', color: '#10b981', fontSize: 28, fontWeight: 'bold', letterSpacing: '2px' }}>
            THE DEV/SIGNAL
          </div>
          <div style={{ display: 'flex', alignItems: 'center', color: '#10b981', fontSize: 18, border: '1px solid #10b981', padding: '4px 12px', borderRadius: '4px' }}>
            <div style={{ width: 8, height: 8, backgroundColor: '#10b981', borderRadius: '50%', marginRight: 8 }} />
            LIVE
          </div>
        </div>

        {/* Date Label */}
        <div style={{ display: 'flex', color: '#f59e0b', fontSize: 20, marginBottom: '20px' }}>
          {date} · ARCHIVE_MODULE_01
        </div>

        {/* Headline */}
        <div style={{ display: 'flex', color: 'white', fontSize: 52, fontWeight: '800', lineHeight: 1.1, marginBottom: '30px' }}>
          {primaryTitle}
        </div>

        {/* AI Summary Snippet */}
        <div style={{ display: 'flex', color: '#888', fontSize: 26, lineHeight: 1.6, borderLeft: '4px solid #10b981', paddingLeft: '20px' }}>
          {brief?.summary?.slice(0, 180)}...
        </div>

        {/* Footer branding */}
        <div style={{ display: 'flex', marginTop: 'auto', color: '#333', fontSize: 16 }}>
          GENERATED BY GEMINI 2.0 FLASH · PROCESSED VIA VERCEL EDGE
        </div>
      </div>
    ),
    { ...size }
  );
        }
                     
